<?php

namespace Database\Seeders;

use App\Models\CompanyCategory;
use Illuminate\Database\Seeder;

/**
 * Translates the 885 CompanyCategory entries (level_1, level_2, level_3) into
 * FR / EN / ES / AR, using mapping files generated by translation work.
 *
 * Mapping files (committed to the repo at database/seeders/data/):
 *   - company_categories_level1.php  (~23 distinct level_1 values)
 *   - company_categories_level2.php  (~295 distinct level_2 values)
 *   - company_categories_level3.php  (~787 distinct level_3 values)
 *
 * Each file returns an associative array:
 *   ['French label' => ['en' => '...', 'es' => '...', 'ar' => '...'], ...]
 *
 * Idempotent: safe to re-run. Always writes FR (canonical) plus any matching
 * EN/ES/AR found in the maps. Unmatched entries fall back to FR via the
 * HasTranslations trait.
 */
class CompanyCategoriesTranslationsSeeder extends Seeder
{
    public function run(): void
    {
        $dataDir = __DIR__.'/data';

        $level1Map = file_exists($dataDir.'/company_categories_level1.php')
            ? require $dataDir.'/company_categories_level1.php'
            : [];
        $level2Map = file_exists($dataDir.'/company_categories_level2.php')
            ? require $dataDir.'/company_categories_level2.php'
            : [];
        $level3Map = file_exists($dataDir.'/company_categories_level3.php')
            ? require $dataDir.'/company_categories_level3.php'
            : [];

        $this->command?->info(sprintf(
            '[CompanyCategoriesTranslationsSeeder] loaded mappings: level_1=%d, level_2=%d, level_3=%d',
            count($level1Map),
            count($level2Map),
            count($level3Map)
        ));

        $rowsTouched = 0;
        $unmapped = [
            'level_1' => [],
            'level_2' => [],
            'level_3' => [],
        ];

        // Eager-load translations to avoid N+1 on setTranslation lookups.
        CompanyCategory::with('translations')->chunkById(200, function ($chunk) use (
            $level1Map,
            $level2Map,
            $level3Map,
            &$rowsTouched,
            &$unmapped
        ) {
            foreach ($chunk as $cat) {
                // Always write the FR canonical value first.
                if ($cat->level_1) {
                    $cat->setTranslation('level_1', 'fr', $cat->level_1);
                    if (isset($level1Map[$cat->level_1])) {
                        foreach ($level1Map[$cat->level_1] as $locale => $value) {
                            if ($value !== null && $value !== '') {
                                $cat->setTranslation('level_1', $locale, $value);
                            }
                        }
                    } else {
                        $unmapped['level_1'][$cat->level_1] = true;
                    }
                }

                if ($cat->level_2) {
                    $cat->setTranslation('level_2', 'fr', $cat->level_2);
                    if (isset($level2Map[$cat->level_2])) {
                        foreach ($level2Map[$cat->level_2] as $locale => $value) {
                            if ($value !== null && $value !== '') {
                                $cat->setTranslation('level_2', $locale, $value);
                            }
                        }
                    } else {
                        $unmapped['level_2'][$cat->level_2] = true;
                    }
                }

                if ($cat->level_3) {
                    $cat->setTranslation('level_3', 'fr', $cat->level_3);
                    if (isset($level3Map[$cat->level_3])) {
                        foreach ($level3Map[$cat->level_3] as $locale => $value) {
                            if ($value !== null && $value !== '') {
                                $cat->setTranslation('level_3', $locale, $value);
                            }
                        }
                    } else {
                        $unmapped['level_3'][$cat->level_3] = true;
                    }
                }

                if ($cat->description) {
                    $cat->setTranslation('description', 'fr', $cat->description);
                }

                $rowsTouched++;
            }
        });

        $this->command?->info("[CompanyCategoriesTranslationsSeeder] processed {$rowsTouched} rows.");

        foreach ($unmapped as $level => $items) {
            $count = count($items);
            if ($count > 0) {
                $this->command?->warn(sprintf(
                    '[CompanyCategoriesTranslationsSeeder] %d unmapped %s value(s) — FR only:',
                    $count,
                    $level
                ));
                foreach (array_slice(array_keys($items), 0, 10) as $val) {
                    $this->command?->line('   - '.$val);
                }
                if ($count > 10) {
                    $this->command?->line(sprintf('   … and %d more', $count - 10));
                }
            }
        }
    }
}
