<?php

namespace Database\Seeders\Roadmaps;

use Illuminate\Database\Seeder;

/**
 * Roadmap Gestion des Systèmes d'Information — devenir Manager / DSI capable de piloter le SI d'une entreprise.
 */
class GestionSiRoadmapSeeder extends Seeder
{
    use RoadmapSeederHelper;

    public function run(): void
    {
        $this->createRoadmap([
            'title' => "Deviens Manager des Systèmes d'Information (DSI)",
            'slug' => 'gestion-des-systemes-information',
            'domain' => 'gestion',
            'description' => "Maîtrise le pilotage des systèmes d'information en entreprise : du rôle stratégique du SI à la gouvernance, en passant par ITIL, le budget, la sécurité, les ERP et la gestion de projet. Une formation pensée pour le contexte africain et les PME camerounaises.",
            'objectives' => "Comprendre le rôle stratégique du SI dans l'entreprise\nUrbaniser et cartographier le système d'information\nAppliquer les bonnes pratiques ITIL de gestion des services\nMettre en place une gouvernance IT et des comités de pilotage\nÉtablir un budget informatique et calculer le ROI\nGarantir la sécurité et la continuité d'activité\nChoisir et déployer un ERP, piloter un projet SI avec des indicateurs",
            'icon' => '🖥️',
            'color' => '#2563EB',
            'difficulty' => 'intermediate',
            'required_packs' => [],
            'pass_threshold' => 70,
            'order' => 20,
            'levels' => [
                [
                    'title' => "Niveau 1 — Le SI, cœur de l'entreprise",
                    'subtitle' => "Comprendre ce qu'est un système d'information",
                    'xp_reward' => 100,
                    'content' => "🎯 **Objectif** : comprendre ce qu'est un Système d'Information (SI) et son rôle dans l'entreprise.\n\n💡 Un SI n'est pas seulement de l'informatique. C'est l'ensemble organisé de **ressources** (humaines, matérielles, logicielles, données et procédures) qui collecte, stocke, traite et diffuse l'information utile à l'entreprise.\n\nLes trois dimensions à retenir :\n• **Technique** : serveurs, réseaux, logiciels, postes de travail.\n• **Organisationnelle** : processus métiers, rôles, procédures.\n• **Humaine** : utilisateurs, compétences, culture numérique.\n\n✅ Exemple concret : dans une PME de distribution à Douala, le SI relie la caisse, la gestion de stock, la facturation et le suivi des paiements Mobile Money. Si l'information circule mal, les ruptures de stock se multiplient.\n\n⚠️ Confusion fréquente : le SI (l'organisation de l'information) ≠ le système informatique (la seule infrastructure technique). Le SI englobe l'humain et les processus.\n\nLe SI sert trois grandes fonctions : **soutenir** les opérations, **aider à la décision** et **créer un avantage concurrentiel**.",
                    'questions' => [
                        ['question' => "Qu'englobe un Système d'Information au sens large ?", 'options' => ['Uniquement les serveurs et le réseau', 'Ressources humaines, matérielles, logicielles, données et procédures', 'Seulement les logiciels installés', 'Uniquement la base de données'], 'correct' => [1], 'explanation' => "Le SI regroupe l'ensemble des ressources organisées pour gérer l'information, pas seulement la technique."],
                        ['question' => "Quelle est la différence entre SI et système informatique ?", 'options' => ['Aucune, ce sont des synonymes', "Le SI inclut l'humain et les processus, le système informatique est la partie technique", 'Le système informatique inclut les utilisateurs, pas le SI', 'Le SI ne concerne que les données'], 'correct' => [1], 'explanation' => "Le système informatique est la composante technique du SI, qui lui intègre aussi l'organisation et l'humain."],
                        ['question' => "Quelles sont des fonctions clés du SI ? (plusieurs réponses)", 'options' => ['Soutenir les opérations quotidiennes', 'Aider à la prise de décision', 'Remplacer totalement les employés', 'Créer un avantage concurrentiel'], 'correct' => [0, 1, 3], 'explanation' => "Le SI soutient les opérations, éclaire la décision et peut créer un avantage concurrentiel, mais il ne remplace pas les employés."],
                    ],
                ],
                [
                    'title' => "Niveau 2 — Typologie des applications du SI",
                    'subtitle' => "ERP, CRM, décisionnel : qui fait quoi",
                    'xp_reward' => 110,
                    'content' => "🎯 **Objectif** : identifier les grandes familles d'applications qui composent un SI d'entreprise.\n\n💡 Chaque application répond à un besoin métier précis :\n• **ERP (PGI)** : gère les processus internes (comptabilité, achats, stocks, RH, production) avec une base de données unique.\n• **CRM** : gère la relation client (prospects, ventes, support).\n• **SCM** : gère la chaîne logistique et les fournisseurs.\n• **Décisionnel (BI)** : transforme les données en tableaux de bord pour décider.\n• **Outils collaboratifs** : messagerie, partage de documents, visioconférence.\n\n✅ Tableau de synthèse :\n\n| Application | Domaine | Exemple d'usage |\n|---|---|---|\n| ERP | Gestion interne | Facturer, suivre les stocks |\n| CRM | Client | Suivre un prospect à Yaoundé |\n| BI | Décision | Tableau de bord des ventes |\n\n⚠️ Une erreur classique consiste à vouloir tout faire avec un seul outil. Un ERP gère l'interne, mais un CRM dédié reste souvent plus efficace pour la prospection commerciale.\n\nLe rôle du DSI est de garantir que ces briques **communiquent** entre elles (interopérabilité) plutôt que de créer des silos isolés.",
                    'questions' => [
                        ['question' => "Quelle application gère prioritairement la relation client ?", 'options' => ['ERP', 'CRM', 'SCM', 'BI'], 'correct' => [1], 'explanation' => "Le CRM (Customer Relationship Management) est dédié à la gestion de la relation client."],
                        ['question' => "À quoi sert un outil de Business Intelligence (BI) ?", 'options' => ['À gérer la paie', 'À transformer les données en tableaux de bord pour décider', 'À envoyer des e-mails', 'À héberger des serveurs'], 'correct' => [1], 'explanation' => "La BI agrège et analyse les données pour produire des indicateurs d'aide à la décision."],
                        ['question' => "Quel est le risque de vouloir tout gérer avec une seule application non adaptée ?", 'options' => ['Une meilleure performance garantie', "Créer des silos ou perdre en efficacité métier", 'Réduire automatiquement les coûts', 'Supprimer le besoin de DSI'], 'correct' => [1], 'explanation' => "Un outil unique mal adapté peut nuire à l'efficacité métier ; l'interopérabilité de briques spécialisées est souvent préférable."],
                    ],
                ],
                [
                    'title' => "Niveau 3 — Urbanisation du SI",
                    'subtitle' => "Cartographier et structurer le SI comme une ville",
                    'xp_reward' => 120,
                    'content' => "🎯 **Objectif** : comprendre l'urbanisation du SI, une démarche pour structurer le SI de façon cohérente et évolutive.\n\n💡 L'urbanisation utilise une métaphore urbaine : on organise le SI comme une ville, en **zones**, **quartiers**, **îlots** et **blocs**. Chaque bloc applicatif a un rôle clair et des règles d'échange définies.\n\nLes quatre vues classiques de l'architecture :\n• **Vue métier** : les processus de l'entreprise.\n• **Vue fonctionnelle** : les grandes fonctions du SI (vente, RH, finance).\n• **Vue applicative** : les logiciels qui réalisent ces fonctions.\n• **Vue technique** : l'infrastructure (serveurs, réseaux).\n\n✅ Objectif : un SI **modulaire** où l'on peut remplacer une application sans casser les autres, grâce à des interfaces standardisées (API, bus d'échange).\n\n⚠️ Sans urbanisation, on obtient un « plat de spaghettis » : des connexions point-à-point partout, impossibles à maintenir. Changer un logiciel devient un cauchemar.\n\nLe cadre de référence le plus connu pour l'architecture d'entreprise est **TOGAF**. L'urbaniste du SI veille à l'alignement entre la stratégie métier et l'architecture technique.",
                    'questions' => [
                        ['question' => "Quelle métaphore est utilisée par l'urbanisation du SI ?", 'options' => ["L'organisation d'une ville en zones et quartiers", "Le fonctionnement d'un moteur", "La structure d'un arbre", "Le corps humain"], 'correct' => [0], 'explanation' => "L'urbanisation organise le SI comme une ville : zones, quartiers, îlots et blocs."],
                        ['question' => "Quel est le principal défaut d'un SI non urbanisé ?", 'options' => ['Trop de modularité', 'Un « plat de spaghettis » de connexions point-à-point ingérable', 'Une documentation excessive', 'Trop peu de logiciels'], 'correct' => [1], 'explanation' => "Sans urbanisation, les connexions point-à-point se multiplient et rendent le SI impossible à maintenir."],
                        ['question' => "Quelles sont des vues classiques de l'architecture d'entreprise ? (plusieurs réponses)", 'options' => ['Vue métier', 'Vue fonctionnelle', 'Vue météorologique', 'Vue technique'], 'correct' => [0, 1, 3], 'explanation' => "Les vues métier, fonctionnelle, applicative et technique structurent l'architecture ; la « vue météorologique » n'existe pas."],
                    ],
                ],
                [
                    'title' => "Niveau 4 — ITIL et gestion des services",
                    'subtitle' => "Délivrer un service IT de qualité",
                    'xp_reward' => 130,
                    'content' => "🎯 **Objectif** : découvrir ITIL, le référentiel de bonnes pratiques pour gérer les services informatiques comme un service rendu au métier.\n\n💡 ITIL (Information Technology Infrastructure Library) propose de gérer l'IT non comme une technique, mais comme un **service** apporté à des clients internes. Principe central : créer de la **valeur** pour le métier.\n\nQuelques pratiques clés :\n• **Gestion des incidents** : restaurer le service au plus vite (ex. : une caisse en panne à Douala).\n• **Gestion des problèmes** : trouver et supprimer la cause racine d'incidents récurrents.\n• **Gestion des changements** : encadrer toute modification pour éviter les régressions.\n• **Centre de services (Service Desk)** : point de contact unique des utilisateurs.\n\n✅ Distinction essentielle :\n\n| Notion | But |\n|---|---|\n| Incident | Rétablir vite le service |\n| Problème | Éliminer la cause racine |\n| Changement | Modifier sans risque |\n\n⚠️ Ne confondez pas incident et problème : un même problème (serveur sous-dimensionné) peut générer plusieurs incidents (lenteurs répétées). On traite l'incident en urgence, le problème sur le fond.\n\nITIL aide à formaliser des **niveaux de service** mesurables et à instaurer une culture d'amélioration continue.",
                    'questions' => [
                        ['question' => "Quelle est la vision centrale d'ITIL ?", 'options' => ["Gérer l'IT comme un service créant de la valeur pour le métier", "Acheter le matériel le moins cher", "Recruter le plus de techniciens possible", "Supprimer le support utilisateur"], 'correct' => [0], 'explanation' => "ITIL considère l'IT comme un service orienté valeur pour les clients internes."],
                        ['question' => "Quelle est la différence entre incident et problème selon ITIL ?", 'options' => ["Aucune différence", "L'incident vise à rétablir vite le service, le problème à éliminer la cause racine", "Le problème est toujours plus rapide à régler", "L'incident concerne uniquement le matériel"], 'correct' => [1], 'explanation' => "L'incident est traité en urgence pour restaurer le service ; le problème s'attaque à la cause racine durable."],
                        ['question' => "À quoi sert le centre de services (Service Desk) ?", 'options' => ['À développer des logiciels', "À être le point de contact unique des utilisateurs", 'À acheter les serveurs', 'À gérer la paie'], 'correct' => [1], 'explanation' => "Le Service Desk est le point d'entrée unique pour les demandes et incidents des utilisateurs."],
                    ],
                ],
                [
                    'title' => "Niveau 5 — Gouvernance IT",
                    'subtitle' => "Aligner le SI sur la stratégie de l'entreprise",
                    'xp_reward' => 140,
                    'content' => "🎯 **Objectif** : comprendre la gouvernance IT, qui assure l'alignement du SI sur la stratégie et la création de valeur maîtrisée.\n\n💡 La gouvernance IT répond à des questions de **direction** : quelles décisions, par qui, et avec quelle responsabilité ? Elle s'appuie sur des instances et des référentiels.\n\nLes piliers de la gouvernance :\n• **Alignement stratégique** : le SI sert les objectifs de l'entreprise.\n• **Création de valeur** : chaque euro investi doit produire un bénéfice.\n• **Gestion des risques** : sécurité, conformité, continuité.\n• **Gestion des ressources** : optimiser hommes, budgets, matériels.\n• **Mesure de la performance** : indicateurs et tableaux de bord.\n\n✅ Référentiel phare : **COBIT**, qui structure la gouvernance et l'audit du SI. Les décisions stratégiques se prennent souvent en **comité de direction informatique (comité de pilotage SI)**, présidé par la direction générale, pas seulement par la DSI.\n\n⚠️ Erreur fréquente : laisser la DSI décider seule des priorités. La gouvernance implique le **métier** dans l'arbitrage des projets, sinon le SI dérive loin des besoins réels.\n\nUne bonne gouvernance distingue ce qui est **stratégique** (décidé par la direction) de l'**opérationnel** (géré par la DSI).",
                    'questions' => [
                        ['question' => "Quel est le but premier de la gouvernance IT ?", 'options' => ["Aligner le SI sur la stratégie et maîtriser la création de valeur", "Réduire le nombre d'employés IT", "Acheter les dernières technologies", "Externaliser tout le SI"], 'correct' => [0], 'explanation' => "La gouvernance IT vise l'alignement stratégique du SI et une création de valeur maîtrisée."],
                        ['question' => "Quel référentiel est dédié à la gouvernance et à l'audit du SI ?", 'options' => ['COBIT', 'HTML', 'SCRUM', 'TCP/IP'], 'correct' => [0], 'explanation' => "COBIT est le référentiel de référence pour la gouvernance et l'audit des SI."],
                        ['question' => "Qui doit participer à l'arbitrage des projets SI ?", 'options' => ['Uniquement la DSI', 'Uniquement les développeurs', 'La direction et le métier, pas seulement la DSI', 'Uniquement les fournisseurs'], 'correct' => [2], 'explanation' => "La gouvernance implique la direction et le métier pour arbitrer les priorités, afin que le SI réponde aux besoins réels."],
                    ],
                ],
                [
                    'title' => "Niveau 6 — Budget IT et ROI",
                    'subtitle' => "Maîtriser les coûts et démontrer la valeur",
                    'xp_reward' => 150,
                    'content' => "🎯 **Objectif** : savoir construire un budget informatique et démontrer le retour sur investissement (ROI) d'un projet SI.\n\n💡 Le budget IT se découpe classiquement en :\n• **CAPEX** : dépenses d'investissement (achat de serveurs, licences pérennes).\n• **OPEX** : dépenses d'exploitation récurrentes (abonnements cloud, maintenance, salaires).\n• **Run** (faire fonctionner l'existant) vs **Build** (projets nouveaux).\n\n✅ Le **TCO** (Coût Total de Possession) mesure le coût complet d'une solution sur sa durée de vie : achat + déploiement + formation + maintenance + énergie. Un logiciel « gratuit » peut coûter cher en TCO.\n\nLe **ROI** se calcule simplement :\n\n```\nROI (%) = (Gains - Coûts) / Coûts x 100\n```\n\nExemple : un ERP coûte 10 000 000 FCFA et fait économiser 4 000 000 FCFA par an. Sur 3 ans : gains 12 000 000, ROI = (12 000 000 - 10 000 000) / 10 000 000 = 20 %.\n\n⚠️ Tout n'est pas chiffrable : certains bénéfices sont **qualitatifs** (satisfaction client, image). Il faut les mentionner sans les confondre avec le ROI financier.\n\nLe DSI doit justifier chaque dépense en langage **métier et financier**, pas seulement technique.",
                    'questions' => [
                        ['question' => "Quelle catégorie correspond aux dépenses récurrentes d'exploitation ?", 'options' => ['CAPEX', 'OPEX', 'ROI', 'TCO'], 'correct' => [1], 'explanation' => "L'OPEX regroupe les dépenses d'exploitation récurrentes (abonnements, maintenance, etc.)."],
                        ['question' => "Que mesure le TCO ?", 'options' => ["Le coût total de possession sur la durée de vie de la solution", "Uniquement le prix d'achat", "Le nombre d'utilisateurs", "Le temps de panne"], 'correct' => [0], 'explanation' => "Le TCO additionne tous les coûts (achat, déploiement, formation, maintenance, énergie) sur la durée de vie."],
                        ['question' => "Un projet coûte 5 000 000 FCFA et rapporte 8 000 000 FCFA de gains. Quel est le ROI ?", 'options' => ['160 %', '60 %', '30 %', '300 %'], 'correct' => [1], 'explanation' => "ROI = (8 000 000 - 5 000 000) / 5 000 000 x 100 = 60 %."],
                    ],
                ],
                [
                    'title' => "Niveau 7 — Sécurité et continuité d'activité",
                    'subtitle' => "Protéger le SI et garantir la reprise",
                    'xp_reward' => 160,
                    'content' => "🎯 **Objectif** : comprendre les fondamentaux de la sécurité du SI et de la continuité d'activité.\n\n💡 La sécurité repose sur le triptyque **DIC** :\n• **Disponibilité** : le SI est accessible quand on en a besoin.\n• **Intégrité** : les données ne sont pas altérées.\n• **Confidentialité** : seules les personnes autorisées y accèdent.\n\n✅ Mesures essentielles :\n• Sauvegardes régulières testées (la règle **3-2-1** : 3 copies, 2 supports, 1 hors site).\n• Gestion des accès (mots de passe forts, authentification à deux facteurs).\n• Mises à jour et antivirus à jour.\n• Sensibilisation des utilisateurs (le phishing reste la première porte d'entrée).\n\n⚠️ Pièges de sécurité fréquents :\n• Ne **jamais** désactiver le pare-feu pour « régler vite » un souci.\n• Ne **jamais** stocker l'unique sauvegarde sur le même serveur que les données.\n• Un mot de passe partagé par e-mail est une faille majeure.\n\nPour la continuité, deux indicateurs clés : le **RTO** (durée de reprise acceptable) et le **RPO** (perte de données maximale tolérée). Le **PRA** (Plan de Reprise d'Activité) décrit comment redémarrer après un sinistre, le **PCA** comment continuer pendant.\n\nDans le contexte africain, les coupures électriques imposent onduleurs, groupes et sauvegardes hors site (cloud).",
                    'questions' => [
                        ['question' => "Que désigne le triptyque DIC de la sécurité ?", 'options' => ['Données, Internet, Cloud', 'Disponibilité, Intégrité, Confidentialité', 'Détection, Incident, Correction', 'Débit, Identité, Connexion'], 'correct' => [1], 'explanation' => "Le DIC = Disponibilité, Intégrité, Confidentialité, les trois piliers de la sécurité de l'information."],
                        ['question' => "Que faut-il faire pour protéger les données ? (plusieurs réponses)", 'options' => ['Désactiver le pare-feu pour aller plus vite', 'Faire des sauvegardes testées hors site', 'Activer l\'authentification à deux facteurs', 'Sensibiliser les utilisateurs au phishing'], 'correct' => [1, 2, 3], 'explanation' => "Sauvegardes hors site, double authentification et sensibilisation protègent le SI ; désactiver le pare-feu est une faute grave."],
                        ['question' => "Que mesure le RPO ?", 'options' => ['La durée de reprise acceptable', 'La perte de données maximale tolérée', 'Le nombre de serveurs', 'Le coût du projet'], 'correct' => [1], 'explanation' => "Le RPO (Recovery Point Objective) définit la quantité maximale de données qu'on accepte de perdre."],
                    ],
                ],
                [
                    'title' => "Niveau 8 — Choisir et déployer un ERP",
                    'subtitle' => "Le système nerveux de l'entreprise",
                    'xp_reward' => 170,
                    'content' => "🎯 **Objectif** : savoir sélectionner et déployer un ERP (Progiciel de Gestion Intégré) adapté à l'entreprise.\n\n💡 Un ERP unifie les processus dans une **base de données unique** : comptabilité, achats, ventes, stocks, RH, production. Avantage majeur : la donnée est saisie **une seule fois** et partagée par tous les modules.\n\nDémarche de choix :\n• **Exprimer le besoin** : cahier des charges fonctionnel issu du métier.\n• **Comparer** : standard du marché (SAP, Odoo, Dolibarr) vs développement spécifique.\n• **Évaluer** : couverture fonctionnelle, coût (TCO), support local, hébergement, conformité **OHADA** pour la comptabilité.\n\n✅ Conseils de déploiement :\n• Privilégier le **paramétrage** plutôt que le développement spécifique (moins coûteux à maintenir).\n• Reprendre et **nettoyer les données** avant migration.\n• Former les utilisateurs et accompagner le **changement**.\n\n⚠️ Les projets ERP échouent souvent à cause de :\n• La sous-estimation de la conduite du changement.\n• La sur-personnalisation qui rend les mises à jour impossibles.\n• Des données initiales de mauvaise qualité.\n\nPour une PME camerounaise, un ERP open source comme Odoo ou Dolibarr, hébergé en cloud, offre un bon compromis coût/fonctionnalités tout en respectant le plan comptable OHADA.",
                    'questions' => [
                        ['question' => "Quel est l'avantage clé d'un ERP ?", 'options' => ['La donnée est saisie une seule fois et partagée par tous les modules', 'Il supprime le besoin de comptabilité', 'Il fonctionne sans données', 'Il remplace le réseau internet'], 'correct' => [0], 'explanation' => "L'ERP repose sur une base unique : la donnée saisie une fois est partagée par tous les modules."],
                        ['question' => "Pourquoi privilégier le paramétrage plutôt que la sur-personnalisation d'un ERP ?", 'options' => ["Parce que c'est plus joli", "Parce que la sur-personnalisation rend les mises à jour difficiles et coûteuses", "Parce que le paramétrage est interdit", "Parce que cela supprime la formation"], 'correct' => [1], 'explanation' => "Trop de développements spécifiques complique les montées de version et alourdit la maintenance."],
                        ['question' => "Quelles sont des causes fréquentes d'échec d'un projet ERP ? (plusieurs réponses)", 'options' => ['Sous-estimer la conduite du changement', 'Sur-personnaliser le logiciel', 'Former les utilisateurs', 'Migrer des données de mauvaise qualité'], 'correct' => [0, 1, 3], 'explanation' => "La mauvaise conduite du changement, la sur-personnalisation et des données de mauvaise qualité font échouer les ERP ; former les utilisateurs est au contraire bénéfique."],
                    ],
                ],
                [
                    'title' => "Niveau 9 — Gestion de projet SI",
                    'subtitle' => "Cadrer, planifier et livrer un projet",
                    'xp_reward' => 185,
                    'content' => "🎯 **Objectif** : maîtriser les bases de la gestion de projet appliquée aux systèmes d'information.\n\n💡 Tout projet SI s'équilibre sur le **triangle d'or** : **Délai – Coût – Qualité (périmètre)**. Modifier un sommet impacte les autres. Si le client veut plus de fonctions sans bouger le budget, la qualité ou le délai trinque.\n\nDeux grandes approches :\n• **Cycle en V / cascade** : phases séquentielles (analyse, conception, réalisation, tests). Adapté quand le besoin est stable.\n• **Agile / Scrum** : livraisons itératives par **sprints**, feedback fréquent. Adapté quand le besoin évolue.\n\n✅ Étapes clés d'un projet :\n• **Cadrage** : objectifs, périmètre, parties prenantes.\n• **Planification** : tâches, jalons, ressources (diagramme de Gantt).\n• **Pilotage** : suivi de l'avancement, gestion des risques.\n• **Recette** : validation par le métier avant mise en production.\n• **Bilan** : retour d'expérience.\n\n⚠️ Le **chef de projet** n'est pas qu'un technicien : il gère les **parties prenantes**, communique, et anticipe les **risques** (registre des risques). Un risque mal anticipé devient un problème coûteux.\n\nDistinguez la **maîtrise d'ouvrage (MOA)**, qui exprime le besoin métier, de la **maîtrise d'œuvre (MOE)**, qui le réalise techniquement.",
                    'questions' => [
                        ['question' => "Quels sont les trois sommets du triangle d'or d'un projet ?", 'options' => ['Délai, Coût, Qualité (périmètre)', 'Réseau, Serveur, Logiciel', 'Client, Fournisseur, Banque', 'Analyse, Code, Test'], 'correct' => [0], 'explanation' => "Le triangle d'or équilibre Délai, Coût et Qualité/périmètre : toucher l'un affecte les autres."],
                        ['question' => "Quelle approche est la mieux adaptée à un besoin qui évolue souvent ?", 'options' => ['Le cycle en V strict', "L'approche Agile / Scrum par sprints", "L'absence de méthode", "La cascade sans tests"], 'correct' => [1], 'explanation' => "L'Agile, par itérations et feedback fréquent, gère bien les besoins changeants."],
                        ['question' => "Quelle est la différence entre MOA et MOE ?", 'options' => ["La MOA exprime le besoin métier, la MOE le réalise techniquement", "La MOE exprime le besoin, la MOA code", "Ce sont des synonymes", "La MOA gère uniquement le budget matériel"], 'correct' => [0], 'explanation' => "La maîtrise d'ouvrage (MOA) porte le besoin métier, la maîtrise d'œuvre (MOE) réalise la solution."],
                    ],
                ],
                [
                    'title' => "Niveau 10 — Indicateurs et pilotage du SI",
                    'subtitle' => "Mesurer, décider et piloter en DSI",
                    'xp_reward' => 200,
                    'content' => "🎯 **Objectif** : piloter le SI grâce à des indicateurs (KPI) et un tableau de bord, pour décider et améliorer en continu.\n\n💡 « On ne pilote bien que ce que l'on mesure. » Un bon **KPI** est **SMART** : Spécifique, Mesurable, Atteignable, Réaliste, Temporel.\n\n✅ Exemples d'indicateurs de pilotage SI :\n\n| Domaine | Indicateur | Cible |\n|---|---|---|\n| Disponibilité | Taux de dispo des serveurs | > 99,5 % |\n| Support | Délai moyen de résolution | < 4 h |\n| Sécurité | Nombre d'incidents/mois | en baisse |\n| Projet | Respect du budget | écart < 5 % |\n| Valeur | Satisfaction utilisateurs | > 80 % |\n\n💡 Distinguez les indicateurs **d'activité** (volume de tickets) des indicateurs de **performance** (taux de résolution) et de **valeur** (impact métier). Le tableau de bord doit rester **synthétique** et orienté décision.\n\n⚠️ Piège : multiplier les indicateurs jusqu'à noyer l'essentiel. Mieux vaut 5 à 10 KPI suivis et compris que 50 ignorés. Et un KPI sans **cible** ni **action corrective** ne sert à rien.\n\nLe pilotage s'inscrit dans une boucle d'**amélioration continue** (PDCA : Planifier, Faire, Vérifier, Agir).\n\n🏆 **Félicitations !** Tu maîtrises désormais les fondamentaux du management des SI : rôle stratégique, urbanisation, ITIL, gouvernance, budget, sécurité, ERP, gestion de projet et pilotage. Ces compétences ouvrent la voie à des carrières de **Responsable informatique**, **Chef de projet SI**, **Consultant ERP**, **Architecte SI** et, à terme, **DSI / Directeur des Systèmes d'Information**. Continue à te certifier (ITIL, COBIT, PMP, certifications cloud) pour accélérer ton évolution. Le SI est le système nerveux de toute organisation moderne : tu es maintenant capable de le piloter pour créer de la valeur !",
                    'questions' => [
                        ['question' => "Que signifie qu'un KPI doit être SMART ?", 'options' => ['Spécifique, Mesurable, Atteignable, Réaliste, Temporel', 'Simple, Moderne, Agile, Rapide, Technique', 'Stratégique, Mobile, Annuel, Régional, Total', 'Sécurisé, Maintenable, Automatique, Récent, Testé'], 'correct' => [0], 'explanation' => "Un bon indicateur est SMART : Spécifique, Mesurable, Atteignable, Réaliste et Temporel."],
                        ['question' => "Quel est le risque de multiplier excessivement les indicateurs ?", 'options' => ['Une meilleure visibilité automatique', "Noyer l'essentiel et rendre le tableau de bord inutile", 'Réduire les coûts', "Améliorer la sécurité"], 'correct' => [1], 'explanation' => "Trop d'indicateurs dilue l'information ; mieux vaut peu de KPI suivis et compris."],
                        ['question' => "Que représente le cycle PDCA ?", 'options' => ['Planifier, Faire, Vérifier, Agir (amélioration continue)', 'Programmer, Déployer, Coder, Archiver', 'Prévoir, Dépenser, Contrôler, Auditer', 'Produire, Distribuer, Compter, Analyser'], 'correct' => [0], 'explanation' => "Le PDCA (Plan-Do-Check-Act) est la boucle d'amélioration continue du pilotage."],
                    ],
                ],
            ],
        ]);

        $this->command->info('  ✓ Roadmap Gestion des Systèmes d\'Information créée (10 niveaux).');
    }
}
