<?php

namespace Database\Seeders\Roadmaps;

use Illuminate\Database\Seeder;

/**
 * Roadmap Publicité en Ligne — maîtriser Google Ads et Meta Ads pour générer des résultats mesurables.
 */
class PubliciteAdsRoadmapSeeder extends Seeder
{
    use RoadmapSeederHelper;

    public function run(): void
    {
        $this->createRoadmap([
            'title' => 'Maîtrise la Publicité en Ligne (Google & Meta Ads)',
            'slug' => 'publicite-sea-ads',
            'domain' => 'marketing',
            'description' => "Apprends à concevoir, lancer et optimiser des campagnes publicitaires rentables sur Google Ads (SEA) et Meta Ads (Facebook/Instagram). De la logique des enchères au calcul du ROAS, cette roadmap te donne les réflexes d'un media buyer professionnel, avec des exemples ancrés dans le marché camerounais et africain francophone.",
            'objectives' => "Comprendre le mécanisme des enchères et du Quality Score\nChoisir le bon objectif de campagne selon ton funnel\nConstruire un ciblage d'audience précis et pertinent\nStructurer un compte publicitaire clair et scalable\nGérer budget, enchères et créa publicitaire performante\nMettre en place le tracking (pixel, conversions) et optimiser le ROAS",
            'icon' => '📣',
            'color' => '#2563EB',
            'difficulty' => 'intermediate',
            'required_packs' => [],
            'pass_threshold' => 70,
            'order' => 20,
            'levels' => [
                [
                    'title' => 'Niveau 1 — Le principe des enchères publicitaires',
                    'subtitle' => 'Comprendre comment se vend l\'attention en ligne',
                    'xp_reward' => 100,
                    'content' => "🎯 **Objectif** : comprendre que la publicité en ligne fonctionne par enchères en temps réel, pas par tarif fixe.\n\n💡 Chaque fois qu'un utilisateur charge une page ou une recherche, une **enchère** se déclenche en quelques millisecondes. Tu ne paies pas seulement avec ton budget : la plateforme combine ton enchère ET la qualité de ta pub.\n\n• **Google Ads** classe les pubs avec l'Ad Rank = Enchère × Quality Score (qualité de l'annonce, pertinence, page de destination).\n• **Meta Ads** utilise la Total Value = Enchère × Taux d'action estimé × Qualité/pertinence.\n• Conséquence clé : une meilleure annonce peut battre un concurrent qui paie plus cher.\n\n✅ Modèles de paiement courants :\n• **CPC** : coût par clic\n• **CPM** : coût pour 1000 impressions\n• **CPA** : coût par acquisition (conversion)\n\n⚠️ Exemple : à Douala, un vendeur de meubles avec une annonce très pertinente (\"meubles Douala livraison\") peut payer moins cher par clic qu'un concurrent au message flou, grâce au Quality Score.",
                    'questions' => [
                        ['question' => 'Sur Google Ads, comment est déterminé le classement d\'une annonce (Ad Rank) ?', 'options' => ['Uniquement par le montant de l\'enchère', 'Par l\'enchère multipliée par le Quality Score', 'Par l\'ancienneté du compte', 'Par le nombre de mots-clés'], 'correct' => [1], 'explanation' => 'L\'Ad Rank combine le montant de l\'enchère et le Quality Score, donc la qualité compte autant que l\'argent.'],
                        ['question' => 'Que signifie le modèle de paiement CPC ?', 'options' => ['Coût pour 1000 impressions', 'Coût par conversion', 'Coût par clic', 'Coût par campagne'], 'correct' => [2], 'explanation' => 'CPC (Cost Per Click) signifie que tu paies à chaque clic sur ton annonce.'],
                        ['question' => 'Pourquoi une annonce de meilleure qualité peut-elle coûter moins cher qu\'une annonce concurrente ?', 'options' => ['Car la plateforme récompense la pertinence via le Quality Score', 'Car la qualité n\'a aucun impact sur le prix', 'Car les plateformes facturent au hasard', 'Car seule l\'ancienneté du compte joue'], 'correct' => [0], 'explanation' => 'Le Quality Score récompense la pertinence, ce qui peut réduire le coût par clic réel.'],
                    ],
                ],
                [
                    'title' => 'Niveau 2 — Les objectifs de campagne',
                    'subtitle' => 'Choisir le bon objectif selon ton funnel marketing',
                    'xp_reward' => 110,
                    'content' => "🎯 **Objectif** : aligner chaque campagne sur un objectif business clair, selon l'étape du funnel.\n\n💡 Le **funnel marketing** se découpe en trois étapes :\n• **TOFU (haut)** : notoriété — faire connaître. Objectifs : couverture, vues vidéo, impressions.\n• **MOFU (milieu)** : considération — susciter l'intérêt. Objectifs : trafic, engagement, prospects.\n• **BOFU (bas)** : conversion — vendre. Objectifs : ventes, leads, achats.\n\n✅ Sur Meta Ads, tu choisis parmi : Notoriété, Trafic, Engagement, Prospects, Promotion de l'app, Ventes.\n✅ Sur Google Ads : Ventes, Prospects, Trafic vers le site, Notoriété de la marque, Visites en magasin.\n\n⚠️ Erreur fréquente : choisir l'objectif \"Trafic\" alors qu'on veut des ventes. La plateforme optimise précisément pour l'objectif choisi — si tu demandes du trafic, elle t'enverra des cliqueurs, pas des acheteurs.\n\nExemple : une école de formation à Yaoundé qui lance une nouvelle filière commence par la **notoriété** (TOFU), puis recible les intéressés avec une campagne **Prospects** (BOFU).",
                    'questions' => [
                        ['question' => 'Quel objectif convient le mieux pour faire connaître une nouvelle marque inconnue ?', 'options' => ['Ventes', 'Notoriété', 'Prospects', 'Conversions d\'achat'], 'correct' => [1], 'explanation' => 'La notoriété (TOFU) sert à se faire connaître auprès d\'une audience qui ne connaît pas encore la marque.'],
                        ['question' => 'Pourquoi est-il risqué de choisir l\'objectif "Trafic" si on veut vendre ?', 'options' => ['Le trafic est interdit en Afrique', 'La plateforme optimise pour les clics, pas pour les achats', 'Le trafic coûte toujours plus cher que les ventes', 'Cela bloque le compte'], 'correct' => [1], 'explanation' => 'La plateforme optimise pour l\'objectif demandé : choisir Trafic ramène des cliqueurs, pas forcément des acheteurs.'],
                        ['question' => 'Quels objectifs correspondent au bas du funnel (BOFU) ? (plusieurs réponses)', 'options' => ['Ventes / Achats', 'Couverture / Impressions', 'Génération de prospects (leads)', 'Vues vidéo de notoriété'], 'correct' => [0, 2], 'explanation' => 'Le BOFU vise la conversion : ventes/achats et génération de prospects en sont les objectifs typiques.'],
                    ],
                ],
                [
                    'title' => 'Niveau 3 — Le ciblage d\'audience',
                    'subtitle' => 'Atteindre les bonnes personnes au bon moment',
                    'xp_reward' => 120,
                    'content' => "🎯 **Objectif** : maîtriser les types d'audiences pour toucher des prospects qualifiés sans gaspiller le budget.\n\n💡 Trois grandes familles d'audiences :\n• **Audiences froides** : personnes qui ne te connaissent pas, ciblées par centres d'intérêt, données démographiques, mots-clés.\n• **Audiences chaudes (retargeting)** : visiteurs du site, personnes ayant interagi avec ta page, abonnés. Très rentables.\n• **Audiences similaires (Lookalike)** : Meta trouve des personnes ressemblant à tes meilleurs clients.\n\n✅ Sur Google Ads, le ciblage repose surtout sur les **mots-clés** (intention de recherche) et les audiences d'affinité.\n✅ Sur Meta, on cible par âge, sexe, localisation (ex : Douala + Yaoundé), intérêts (ex : entrepreneuriat, mode) et comportements.\n\n⚠️ Évite le sur-ciblage : une audience trop étroite (quelques milliers de personnes) fait grimper les coûts et limite la diffusion. Vise un volume suffisant pour que l'algorithme apprenne.\n\nExemple : un coach business à Douala recible les visiteurs de sa page de vente (audience chaude) avec une offre limitée — taux de conversion bien supérieur au froid.",
                    'questions' => [
                        ['question' => 'Qu\'est-ce qu\'une audience de retargeting (audience chaude) ?', 'options' => ['Des personnes qui n\'ont jamais entendu parler de toi', 'Des personnes ayant déjà interagi avec ta marque ou ton site', 'Des robots automatisés', 'Des personnes choisies au hasard'], 'correct' => [1], 'explanation' => 'Le retargeting cible des personnes ayant déjà eu un contact (visite, engagement), donc plus susceptibles de convertir.'],
                        ['question' => 'À quoi sert une audience similaire (Lookalike) sur Meta ?', 'options' => ['À bloquer les concurrents', 'À trouver des personnes ressemblant à tes meilleurs clients', 'À recibler uniquement tes abonnés', 'À supprimer les mauvais clients'], 'correct' => [1], 'explanation' => 'Le Lookalike utilise une audience source de qualité pour trouver de nouvelles personnes au profil similaire.'],
                        ['question' => 'Pourquoi un ciblage trop étroit est-il souvent contre-productif ?', 'options' => ['Il fait grimper les coûts et limite l\'apprentissage de l\'algorithme', 'Il est interdit par la plateforme', 'Il augmente toujours les ventes', 'Il n\'a aucun effet'], 'correct' => [0], 'explanation' => 'Une audience trop petite empêche l\'algorithme d\'optimiser et augmente le coût par résultat.'],
                    ],
                ],
                [
                    'title' => 'Niveau 4 — Structure du compte et des campagnes',
                    'subtitle' => 'Organiser un compte clair, lisible et scalable',
                    'xp_reward' => 130,
                    'content' => "🎯 **Objectif** : comprendre la hiérarchie d'un compte publicitaire pour piloter et optimiser facilement.\n\n💡 La structure est identique en logique sur les deux plateformes :\n\n```\nCompte\n └─ Campagne (objectif + budget)\n     └─ Groupe d'annonces / Ad Set (ciblage)\n         └─ Annonces (créa : visuels, textes)\n```\n\n• **Campagne** : définit l'objectif et souvent le budget.\n• **Groupe d'annonces (Google) / Ad Set (Meta)** : définit l'audience, le ciblage, le placement.\n• **Annonce** : le contenu vu par l'utilisateur (image, vidéo, texte).\n\n✅ Bonnes pratiques :\n• Une thématique = un groupe d'annonces (sur Google, regroupe les mots-clés par sujet).\n• Sépare les audiences froides et chaudes en campagnes distinctes.\n• Garde des noms clairs : `CMR-Vente-Douala-Retargeting`.\n\n⚠️ Ne mélange pas trop d'objectifs ou d'audiences dans une seule campagne : tu perds en lisibilité et l'optimisation devient impossible. Une structure propre = des décisions rapides quand tu analyses les chiffres.",
                    'questions' => [
                        ['question' => 'Quel est l\'ordre hiérarchique correct d\'un compte publicitaire ?', 'options' => ['Annonce > Campagne > Groupe d\'annonces', 'Campagne > Groupe d\'annonces (Ad Set) > Annonces', 'Groupe d\'annonces > Compte > Campagne', 'Annonces > Compte > Campagne'], 'correct' => [1], 'explanation' => 'La hiérarchie va de la campagne (objectif) au groupe d\'annonces (ciblage) puis aux annonces (créa).'],
                        ['question' => 'À quel niveau définit-on généralement le ciblage de l\'audience ?', 'options' => ['Au niveau du compte', 'Au niveau de l\'annonce', 'Au niveau du groupe d\'annonces / Ad Set', 'Au niveau du paiement'], 'correct' => [2], 'explanation' => 'Le ciblage (audience, placement) se règle au niveau du groupe d\'annonces / Ad Set.'],
                        ['question' => 'Pourquoi est-il déconseillé de mélanger trop d\'audiences et d\'objectifs dans une seule campagne ?', 'options' => ['Cela viole les règles fiscales OHADA', 'On perd en lisibilité et l\'optimisation devient impossible', 'Cela augmente automatiquement le ROAS', 'Cela double le budget'], 'correct' => [1], 'explanation' => 'Une structure confuse empêche d\'isoler ce qui fonctionne et complique l\'optimisation.'],
                    ],
                ],
                [
                    'title' => 'Niveau 5 — Budget et stratégies d\'enchères',
                    'subtitle' => 'Allouer son argent intelligemment',
                    'xp_reward' => 140,
                    'content' => "🎯 **Objectif** : savoir répartir le budget et choisir la bonne stratégie d'enchères.\n\n💡 Deux types de budget :\n• **Budget quotidien** : montant moyen dépensé par jour (peut varier de ±25 % selon les opportunités).\n• **Budget total (à vie)** : montant réparti automatiquement sur la durée de la campagne.\n\n✅ Stratégies d'enchères courantes :\n• **Enchères manuelles (CPC manuel)** : tu contrôles le clic, utile au démarrage avec peu de données.\n• **Maximiser les conversions** : l'algorithme dépense tout le budget pour le maximum de conversions.\n• **CPA cible (tCPA)** : tu fixes un coût par acquisition visé.\n• **ROAS cible (tROAS)** : tu vises un retour sur dépense publicitaire précis.\n\n⚠️ Les stratégies automatiques (Smart Bidding) ont besoin de **données** : il faut généralement un minimum de conversions (souvent ~30-50/mois) pour bien fonctionner. Au lancement, commence simple.\n\nExemple : une boutique en ligne à Yaoundé démarre avec un budget quotidien de 5 000 FCFA et des enchères manuelles, puis passe en \"Maximiser les conversions\" une fois 50 ventes enregistrées par le pixel.",
                    'questions' => [
                        ['question' => 'Que permet la stratégie "CPA cible" (tCPA) ?', 'options' => ['Fixer un coût par acquisition que l\'algorithme essaie de respecter', 'Garantir 1000 impressions gratuites', 'Bloquer les enchères concurrentes', 'Payer uniquement au clic manuel'], 'correct' => [0], 'explanation' => 'Le CPA cible indique à l\'algorithme le coût par conversion visé, qu\'il optimise automatiquement.'],
                        ['question' => 'Pourquoi vaut-il mieux commencer simple avant d\'activer le Smart Bidding ?', 'options' => ['Parce que le Smart Bidding est payant en plus', 'Parce que les stratégies automatiques ont besoin de données de conversion pour bien fonctionner', 'Parce que c\'est interdit au lancement', 'Parce que les enchères manuelles convertissent toujours mieux'], 'correct' => [1], 'explanation' => 'Sans historique de conversions suffisant, l\'algorithme automatique manque de données pour optimiser.'],
                        ['question' => 'Quelle est la différence entre budget quotidien et budget total (à vie) ?', 'options' => ['Aucune différence', 'Le quotidien est une moyenne par jour, le total est réparti sur la durée de campagne', 'Le total est obligatoire sur Google uniquement', 'Le quotidien ne peut jamais varier'], 'correct' => [1], 'explanation' => 'Le budget quotidien fixe une dépense moyenne journalière, tandis que le budget total est étalé sur la durée définie.'],
                    ],
                ],
                [
                    'title' => 'Niveau 6 — La créa publicitaire',
                    'subtitle' => 'Concevoir des annonces qui captent et convertissent',
                    'xp_reward' => 150,
                    'content' => "🎯 **Objectif** : créer des annonces (visuels + textes) qui arrêtent le scroll et donnent envie de cliquer.\n\n💡 Une bonne créa repose sur :\n• **Le hook (accroche)** : les 3 premières secondes d'une vidéo ou la première ligne d'un texte décident de tout.\n• **L'angle** : le problème résolu, le bénéfice, l'émotion (gain de temps, économie, statut).\n• **Le CTA (appel à l'action)** : clair et unique — \"Commandez maintenant\", \"Inscrivez-vous\".\n\n✅ Formats : image unique, carrousel, vidéo courte, collection. Sur mobile (dominant en Afrique), privilégie le **format vertical 9:16** et les sous-titres (beaucoup regardent sans son).\n\n✅ Règle de Meta : limite le texte sur l'image, le visuel doit être lisible sur petit écran.\n\n⚠️ La **fatigue créative** : quand la même pub tourne trop longtemps, l'audience la lasse, le CTR chute et le coût grimpe. Renouvelle régulièrement tes visuels.\n\nExemple : un restaurant à Douala montre en vidéo verticale la préparation d'un ndolè fumant + sous-titres + CTA \"Commandez sur WhatsApp\" — bien plus performant qu'une simple photo de logo.",
                    'questions' => [
                        ['question' => 'Pourquoi le "hook" (accroche) est-il crucial dans une publicité vidéo ?', 'options' => ['Il définit le budget', 'Les premières secondes décident si l\'utilisateur continue ou scrolle', 'Il est obligatoire pour le pixel', 'Il fixe l\'enchère'], 'correct' => [1], 'explanation' => 'L\'attention se joue dans les premières secondes : un hook fort retient l\'utilisateur.'],
                        ['question' => 'Qu\'est-ce que la "fatigue créative" ?', 'options' => ['Une panne du compte publicitaire', 'L\'usure d\'une pub trop diffusée : le CTR chute et le coût augmente', 'Un format vidéo interdit', 'Un type d\'enchère automatique'], 'correct' => [1], 'explanation' => 'Quand la même créa tourne trop longtemps, l\'audience s\'en lasse, faisant baisser la performance.'],
                        ['question' => 'Pourquoi privilégier le format vertical avec sous-titres en Afrique francophone ?', 'options' => ['Parce que le mobile domine et beaucoup regardent sans le son', 'Parce que c\'est moins cher à produire', 'Parce que Google l\'impose', 'Parce que c\'est interdit en format horizontal'], 'correct' => [0], 'explanation' => 'L\'usage majoritairement mobile et la consommation silencieuse rendent le vertical et les sous-titres très efficaces.'],
                    ],
                ],
                [
                    'title' => 'Niveau 7 — Landing page et conversion',
                    'subtitle' => 'Transformer le clic en action concrète',
                    'xp_reward' => 160,
                    'content' => "🎯 **Objectif** : optimiser la page de destination pour ne pas gaspiller des clics payants.\n\n💡 Une pub réussie qui mène à une mauvaise page = budget perdu. La **landing page** doit prolonger la promesse de l'annonce.\n\n✅ Éléments d'une landing page qui convertit :\n• **Cohérence message** : le titre de la page reprend la promesse de la pub.\n• **Vitesse de chargement** : sur connexion mobile (3G/4G fréquente en Afrique), une page lente fait fuir. Vise moins de 3 secondes.\n• **Un seul objectif** : un CTA principal, pas dix liens qui dispersent.\n• **Preuve sociale** : témoignages, avis, logos.\n• **Réassurance** : moyens de paiement visibles (Mobile Money, Orange Money, MTN MoMo), livraison, contact WhatsApp.\n\n⚠️ Le **taux de conversion** = (conversions ÷ visiteurs) × 100. Si beaucoup cliquent mais personne n'achète, le problème est souvent la page, pas la pub.\n\nExemple : une formation vendue à Yaoundé voit son taux de conversion doubler après avoir ajouté le paiement MTN MoMo et un bouton WhatsApp visible dès le haut de page.",
                    'questions' => [
                        ['question' => 'Pourquoi la cohérence entre l\'annonce et la landing page est-elle importante ?', 'options' => ['Pour respecter la loi OHADA', 'Pour prolonger la promesse de la pub et rassurer le visiteur', 'Pour augmenter le CPM', 'Cela n\'a aucune importance'], 'correct' => [1], 'explanation' => 'Si la page ne tient pas la promesse de l\'annonce, le visiteur est déçu et repart sans convertir.'],
                        ['question' => 'Comment se calcule le taux de conversion ?', 'options' => ['(Conversions ÷ visiteurs) × 100', 'Clics ÷ impressions', 'Budget ÷ conversions', 'Impressions × CPC'], 'correct' => [0], 'explanation' => 'Le taux de conversion rapporte le nombre de conversions au nombre de visiteurs, en pourcentage.'],
                        ['question' => 'Quels éléments renforcent la conversion d\'une landing page en contexte africain ? (plusieurs réponses)', 'options' => ['Affichage des moyens de paiement Mobile Money', 'Chargement rapide même en 3G/4G', 'Multiplier les liens et CTA différents', 'Bouton de contact WhatsApp visible'], 'correct' => [0, 1, 3], 'explanation' => 'Mobile Money, vitesse de chargement et contact WhatsApp rassurent et facilitent l\'action ; multiplier les CTA disperse au contraire.'],
                    ],
                ],
                [
                    'title' => 'Niveau 8 — Tracking et pixel',
                    'subtitle' => 'Mesurer ce qui se passe vraiment après le clic',
                    'xp_reward' => 170,
                    'content' => "🎯 **Objectif** : installer le suivi des conversions pour optimiser sur des données fiables.\n\n💡 Sans tracking, tu pilotes à l'aveugle. Le **pixel** (Meta) et la **balise de conversion / Google Tag** (Google) sont des bouts de code placés sur ton site qui remontent les actions des visiteurs.\n\n✅ Ce que mesure le pixel :\n• Pages vues, ajouts au panier, achats, inscriptions, contacts.\n• Ces actions sont appelées **événements**.\n\n```\n<!-- Exemple simplifié : événement d'achat Meta Pixel -->\nfbq('track', 'Purchase', {value: 25000, currency: 'XAF'});\n```\n\n✅ La **CAPI (Conversions API)** côté serveur complète le pixel navigateur : elle envoie les conversions directement depuis ton serveur, plus fiable face aux bloqueurs et restrictions de cookies.\n\n⚠️ Restrictions de confidentialité (iOS, blocage cookies) : une partie du tracking navigateur est perdue. D'où l'intérêt de combiner pixel + CAPI.\n\nExemple : une boutique configure l'événement \"Purchase\" avec la valeur en XAF. Désormais Meta sait quelles pubs génèrent de vraies ventes et peut optimiser pour les acheteurs, pas juste les cliqueurs.",
                    'questions' => [
                        ['question' => 'À quoi sert le pixel Meta (ou la balise de conversion Google) ?', 'options' => ['À bloquer les concurrents', 'À remonter les actions des visiteurs (événements) depuis ton site', 'À créer les visuels automatiquement', 'À payer les factures publicitaires'], 'correct' => [1], 'explanation' => 'Le pixel/balise enregistre les événements (achat, inscription...) pour mesurer et optimiser les conversions.'],
                        ['question' => 'Quel est l\'intérêt de la Conversions API (CAPI) côté serveur ?', 'options' => ['Elle remplace totalement la créa', 'Elle envoie les conversions depuis le serveur, plus fiable face aux bloqueurs de cookies', 'Elle baisse automatiquement le CPC', 'Elle supprime le besoin de landing page'], 'correct' => [1], 'explanation' => 'La CAPI envoie les données côté serveur, ce qui limite les pertes dues aux restrictions navigateur.'],
                        ['question' => 'Que se passe-t-il si tu lances des campagnes sans aucun tracking installé ?', 'options' => ['Tu optimises à l\'aveugle sans savoir ce qui convertit', 'Les conversions sont quand même parfaitement mesurées', 'La plateforme refuse de diffuser', 'Le ROAS est garanti'], 'correct' => [0], 'explanation' => 'Sans tracking, tu ne sais pas quelles pubs génèrent des résultats, donc l\'optimisation est impossible.'],
                    ],
                ],
                [
                    'title' => 'Niveau 9 — Optimisation et A/B testing',
                    'subtitle' => 'Améliorer les performances par l\'expérimentation',
                    'xp_reward' => 185,
                    'content' => "🎯 **Objectif** : utiliser la méthode du test A/B et les bons réflexes d'optimisation pour faire progresser tes campagnes.\n\n💡 L'**A/B test** consiste à comparer deux versions en ne changeant **qu'une seule variable** à la fois : un visuel, un titre, une audience. Sinon tu ne sais pas ce qui a fait la différence.\n\n✅ Méthode :\n• Définis une hypothèse : \"La vidéo convertira mieux que l'image\".\n• Laisse tourner assez longtemps pour atteindre la **significativité statistique** (pas de conclusion sur 10 clics).\n• Garde la version gagnante, teste une nouvelle variable.\n\n✅ La **phase d'apprentissage** : au lancement, l'algorithme explore. Évite de modifier la campagne trop souvent — chaque changement majeur la réinitialise.\n\n⚠️ Erreurs fréquentes :\n• Couper une campagne trop tôt (avant d'avoir des données).\n• Changer 5 choses à la fois.\n• Optimiser sur le CTR alors que l'objectif est la vente.\n\nExemple : un e-commerçant à Douala teste deux accroches (\"Livraison gratuite\" vs \"-20 % aujourd'hui\"). Après 200 conversions, \"Livraison gratuite\" gagne ; il l'adopte puis teste un nouveau visuel.",
                    'questions' => [
                        ['question' => 'Quelle est la règle d\'or d\'un A/B test fiable ?', 'options' => ['Changer plusieurs variables en même temps pour aller vite', 'Ne changer qu\'une seule variable à la fois', 'Arrêter le test après 10 clics', 'Tester uniquement le budget'], 'correct' => [1], 'explanation' => 'En isolant une seule variable, on sait précisément ce qui a causé la différence de performance.'],
                        ['question' => 'Pourquoi faut-il éviter de modifier une campagne trop souvent au lancement ?', 'options' => ['Cela coûte des frais supplémentaires', 'Chaque changement majeur réinitialise la phase d\'apprentissage de l\'algorithme', 'C\'est interdit par la loi', 'Cela supprime le pixel'], 'correct' => [1], 'explanation' => 'Les modifications importantes relancent la phase d\'apprentissage, empêchant l\'algorithme de se stabiliser.'],
                        ['question' => 'Quelles sont des erreurs classiques d\'optimisation ? (plusieurs réponses)', 'options' => ['Couper une campagne avant d\'avoir des données suffisantes', 'Atteindre la significativité statistique avant de conclure', 'Changer plusieurs éléments en même temps', 'Optimiser sur le CTR alors que l\'objectif est la vente'], 'correct' => [0, 2, 3], 'explanation' => 'Conclure trop tôt, modifier trop de variables et optimiser sur la mauvaise métrique sont des erreurs ; attendre la significativité est au contraire une bonne pratique.'],
                    ],
                ],
                [
                    'title' => 'Niveau 10 — ROAS, KPI et pilotage rentable',
                    'subtitle' => 'Mesurer la rentabilité et piloter comme un pro',
                    'xp_reward' => 200,
                    'content' => "🎯 **Objectif** : maîtriser les indicateurs clés pour juger si une campagne est réellement rentable.\n\n💡 Indicateurs essentiels (KPI) :\n• **ROAS** = Chiffre d'affaires généré ÷ Dépense publicitaire. Un ROAS de 4 signifie 4 FCFA gagnés pour 1 FCFA dépensé.\n• **CPA** : coût par acquisition.\n• **CTR** : taux de clics (clics ÷ impressions).\n• **CPM** : coût pour 1000 impressions.\n• **Taux de conversion** : conversions ÷ clics.\n\n✅ Attention au **ROAS seuil de rentabilité** : il dépend de ta marge. Avec 50 % de marge, il faut un ROAS supérieur à 2 pour gagner de l'argent.\n\n| KPI | Mesure |\n|-----|--------|\n| ROAS | Rentabilité de la dépense |\n| CPA | Coût d'un client |\n| CTR | Attractivité de l'annonce |\n\n⚠️ Un beau CTR sans ventes ne sert à rien : pilote sur les KPI alignés à ton objectif business.\n\n🏆 **Félicitations !** Tu maîtrises désormais la chaîne complète : enchères, objectifs, ciblage, structure, budget, créa, landing page, tracking, optimisation et mesure du ROAS. Tu peux viser des métiers comme **Media Buyer**, **Traffic Manager**, **Growth Marketer** ou **consultant Ads freelance** — des compétences très recherchées par les PME, e-commerçants et agences en Afrique francophone. Continue à pratiquer sur de vrais budgets et à analyser tes chiffres : c'est là que se forge l'expertise !",
                    'questions' => [
                        ['question' => 'Comment se calcule le ROAS ?', 'options' => ['Dépense publicitaire ÷ chiffre d\'affaires', 'Chiffre d\'affaires généré ÷ dépense publicitaire', 'Clics ÷ impressions', 'Conversions ÷ budget quotidien'], 'correct' => [1], 'explanation' => 'Le ROAS = revenus générés divisés par la dépense publicitaire ; il mesure le retour sur dépense.'],
                        ['question' => 'Pourquoi un ROAS de 2 peut-il ne pas suffire à être rentable ?', 'options' => ['Parce que le ROAS seuil dépend de ta marge', 'Parce que le ROAS doit toujours dépasser 10', 'Parce que le ROAS ignore les ventes', 'Parce que le ROAS est interdit en Afrique'], 'correct' => [0], 'explanation' => 'Le seuil de rentabilité du ROAS dépend de la marge : avec une faible marge, un ROAS de 2 peut laisser une perte.'],
                        ['question' => 'Pourquoi un excellent CTR ne garantit-il pas le succès d\'une campagne de vente ?', 'options' => ['Parce que le CTR mesure les clics, pas les ventes ni la rentabilité', 'Parce que le CTR fait baisser le ROAS', 'Parce qu\'un bon CTR est toujours un mauvais signe', 'Parce que le CTR remplace le pixel'], 'correct' => [0], 'explanation' => 'Le CTR mesure l\'attractivité de l\'annonce, mais seul le ROAS/CPA dit si la campagne est rentable.'],
                    ],
                ],
            ],
        ]);

        $this->command->info('  ✓ Roadmap Publicité en Ligne créée (10 niveaux).');
    }
}
